### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by roboserg** [SergeyMakeev/ArcadeCarPhysics#3]
Hello and thank you very much for this project! I will use it to do AI for racing with Unity ML Agents.

I have a little problem, I opened the project with Unity 2018 and it seems some textures are missing, console shows no errors - https://puu.sh/DOcxD/7be31a90ea.png

Is there a fix?

**Comment by SergeyMakeev** [comment]
Hey roboserg,
Do you know exact Unity version number? This texture issue looks odd, because I actually did this project using Unity 2018 :)

**Comment by mbaske** [comment]
> Hello and thank you very much for this project! I will use it to do AI for racing with Unity ML Agents.

Wanted to add my thanks for your great work @SergeyMakeev and mention that I actually used the car in an ml-agents project. It's just a single agent setup for now - although it would be interesting to have multiple agents compete against each other in a racing game. Is that maybe something you're working on @roboserg ?
Here's a little video of my project: https://www.youtube.com/watch?v=gEf9V03HWv0

**Comment by roboserg** [comment]
Looks good, did you use ray casts as observations?
Here is my work with several agents - https://puu.sh/EdIep/fff90c3d7b.mp4
https://twitter.com/RobosergTV/status/1148134802282950656

**Comment by mbaske** [comment]
> Looks good, did you use ray casts as observations?

Yes.

> Here is my work with several agents

Nice - that should be a game at some point. Not sure if there are any racing games yet using deep learning.

**Comment by roboserg** [comment]
@mbaske Do you use only horizontal rays? I saw your road is not flat, it goes up and down. So I am wondering are you using 2d ray casts that go only in one plane, or 3d raycasts, like a LIDAR. Otherwise you will have a problem like this https://puu.sh/EdISN/535a7fb0dd.png

**Comment by mbaske** [comment]
@roboserg I ran into this problem and tried to solve it with shooting raycasts at different vertical angles, but that didn't work too well. Now, I'm actually cheating a little, because the raycasts don't originate from the car directly. Instead, they are parallel lines on a plane above the road (see video). So my detection logic is to some extent already aware of the track's nearby curvature and elevation changes. And therefore fitted to that specific environment.
I agree though, the proper way to generalize the detection method would be to either do something like LIDAR with LOTS of rays, or use visual observations. I've tried replacing the raycasts with a front facing camera, but wasn't getting any good training results - at least not during the first 20M steps, so I didn't proceed with visual observations.
